spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "0000"

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

logging:
  level:
    org:
      springframework: INFO
